import urllib.parse
import re
import time
import json
from multiprocessing import Pool, Manager, Lock
from playwright.sync_api import sync_playwright

# ==================== 频道配置 ====================
CHANNELS = [
    ("cctv1",  "CCTV-1",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=11200132825562653886"),
    ("cctv2",  "CCTV-2",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=12030532124776958103"),
    ("cctv4",  "CCTV-4",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=10620168294224708952"),
    ("cctv7",  "CCTV-7",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=8516529981177953694"),
    ("cctv9",  "CCTV-9",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=7252237247689203957"),
    ("cctv10", "CCTV-10", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=14589146016461298119"),
    ("cctv12", "CCTV-12", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=13180385922471124325"),
    ("cctv13", "CCTV-13", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=16265686808730585228"),
    ("cctv17", "CCTV-17", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=4496917190172866934"),
    ("cctv4k", "CCTV-4K", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=2127841942201075403"),
]


def clean_m3u8_url(raw_url):
    """清理 m3u8 URL，提取核心地址"""
    decoded = urllib.parse.unquote(raw_url)
    match = re.search(r'(https://live-play-hls\.cctvnews\.cctv\.com[^&\s]+)', decoded)
    if match:
        return match.group(1)
    return decoded


def extract_channel_worker(args):
    """进程工作函数 - 每个进程独立运行 Playwright"""
    name, display_name, url, max_wait = args
    m3u8_urls = set()

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-gpu',
                    '--disable-web-security',
                    '--disable-features=IsolateOrigins,site-per-process',
                ]
            )
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36",
                viewport={"width": 360, "height": 661},
                is_mobile=True,
            )
            page = context.new_page()

            def handle_request(request):
                url_str = request.url
                if ".m3u8" in url_str:
                    m3u8_urls.add(url_str)

            page.on("request", handle_request)

            # 访问页面
            page.goto(url, wait_until="domcontentloaded", timeout=30000)

            # 等待页面稳定
            time.sleep(2)

            # 尝试点击播放
            selectors = [
                "button.custom-prism-play-control",
                "button[aria-label*='播放']",
                "button[title*='播放']",
                ".prism-play-btn",
                "video",
            ]
            clicked = False
            for sel in selectors:
                try:
                    if page.locator(sel).count() > 0:
                        page.locator(sel).first.click(timeout=5000)
                        clicked = True
                        break
                except:
                    continue

            if not clicked:
                try:
                    page.evaluate("""
                        const v = document.querySelector('video');
                        if (v) { v.muted = true; v.play(); }
                    """)
                except:
                    pass

            # 等待 m3u8 请求
            start_time = time.time()
            while not m3u8_urls and time.time() - start_time < max_wait:
                time.sleep(0.5)
                # 偶尔滚动一下触发懒加载
                if int((time.time() - start_time) * 2) % 5 == 0:
                    try:
                        page.evaluate("window.scrollBy(0, 100)")
                    except:
                        pass

            browser.close()

    except Exception as e:
        return name, display_name, [], str(e)

    # 清理 URL
    results = []
    seen = set()
    for m3u8 in m3u8_urls:
        cleaned = clean_m3u8_url(m3u8)
        if cleaned not in seen:
            seen.add(cleaned)
            results.append(cleaned)

    return name, display_name, results, None


def generate_m3u(results, filename="cctv_live.m3u"):
    """生成 M3U 文件 - 每个频道写入所有 URL"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write("#EXTM3U
")
        f.write("# Generated by CCTV Live Scraper (Stable Edition)\n\n")

        success_count = 0
        for name, display_name, urls, error in results:
            if urls:
                success_count += 1
                for idx, url in enumerate(urls):
                    if idx == 0:
                        f.write(f'#EXTINF:-1 tvg-id="{name}" tvg-name="{display_name}" group-title="CCTV",{display_name}\n')
                    else:
                        f.write(f'#EXTINF:-1 tvg-id="{name}_alt{idx}" tvg-name="{display_name} (备用{idx})" group-title="CCTV",{display_name} (备用{idx})\n')
                    f.write(f"{url}\n\n")

    print(f"\n🎉 M3U 文件生成完成！共 {success_count} 个频道")
    print(f"📁 文件保存为: {filename}")


def run_all_channels(max_workers=4, max_wait=30):
    """主函数 - 使用多进程池"""
    total = len(CHANNELS)
    print(f"\n🚀 启动抓取，共 {total} 个频道，最大并发 {max_workers} 个进程...\n")

    # 构建参数列表
    args_list = [(name, disp_name, url, max_wait) for name, disp_name, url in CHANNELS]

    # 使用进程池
    all_results = []
    with Pool(processes=max_workers) as pool:
        # imap_unordered 可以实时获取结果
        for result in pool.imap_unordered(extract_channel_worker, args_list):
            name, display_name, urls, error = result
            if error:
                print(f"❌ [{name}] 错误: {error}")
            else:
                status = "✅" if urls else "⚠️"
                print(f"{status} [{name}] 找到 {len(urls)} 个源")
            all_results.append(result)

    # 按原始顺序排序
    order_map = {name: idx for idx, (name, _, _) in enumerate(CHANNELS)}
    all_results.sort(key=lambda x: order_map[x[0]])

    # 生成 M3U
    generate_m3u(all_results)

    # 打印汇总
    print("\n" + "=" * 70)
    print("📊 抓取结果汇总")
    print("=" * 70)
    for name, display_name, urls, error in all_results:
        if error:
            print(f"❌ {display_name:12} → 错误: {error[:50]}")
        elif urls:
            print(f"✅ {display_name:12} → {len(urls)} 个直播源")
            for u in urls:
                print(f"   {u[:80]}...")
        else:
            print(f"⚠️ {display_name:12} → 未找到直播源")

    # 同时生成 JSON 备用
    json_data = {}
    for name, display_name, urls, _ in all_results:
        if urls:
            json_data[display_name] = urls

    with open("cctv_live.json", "w", encoding="utf-8") as f:
        json.dump(json_data, f, ensure_ascii=False, indent=2)
    print(f"\n📁 JSON 备用文件: cctv_live.json")

    return all_results


if __name__ == "__main__":
    MAX_WORKERS = 4      # 进程数，建议不超过 CPU 核心数
    MAX_WAIT = 35        # 每个频道最大等待秒数

    results = run_all_channels(max_workers=MAX_WORKERS, max_wait=MAX_WAIT)
