import urllib.parse
import re
import time
import json
from multiprocessing import Pool
from playwright.sync_api import sync_playwright

CHANNELS = [
    ("cctv1",  "CCTV-1",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=11200132825562653886"),
    ("cctv2",  "CCTV-2",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=12030532124776958103"),
    ("cctv4",  "CCTV-4",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=10620168294224708952"),
    ("cctv7",  "CCTV-7",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=8516529981177953694"),
    ("cctv9",  "CCTV-9",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=7252237247689203957"),
    ("cctv10", "CCTV-10", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=14589146016461298119"),
    ("cctv12", "CCTV-12", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=13180385922471124325"),
    ("cctv13", "CCTV-13", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=16265686808730585228"),
    ("cctv17", "CCTV-17", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=4496917190172866934"),
    ("cctv4k", "CCTV-4K", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=2127841942201075403"),
]


def clean_m3u8_url(raw_url):
    decoded = urllib.parse.unquote(raw_url)
    match = re.search(r'(https://live-play-hls\.cctvnews\.cctv\.com[^&\s]+)', decoded)
    if match:
        return match.group(1)
    return decoded


def extract_channel_worker(args):
    name, display_name, url, max_wait = args
    m3u8_urls = set()
    
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-gpu',
                    '--disable-web-security',
                    '--disable-features=IsolateOrigins,site-per-process',
                ]
            )
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36",
                viewport={"width": 360, "height": 661},
                is_mobile=True,
            )
            page = context.new_page()

            def handle_request(request):
                url_str = request.url
                if ".m3u8" in url_str:
                    m3u8_urls.add(url_str)

            page.on("request", handle_request)
            page.goto(url, wait_until="domcontentloaded", timeout=30000)
            time.sleep(2)

            selectors = [
                "button.custom-prism-play-control",
                "button[aria-label*='播放']",
                "button[title*='播放']",
                ".prism-play-btn",
                "video",
            ]
            clicked = False
            for sel in selectors:
                try:
                    if page.locator(sel).count() > 0:
                        page.locator(sel).first.click(timeout=5000)
                        clicked = True
                        break
                except:
                    continue

            if not clicked:
                try:
                    page.evaluate("""
                        const v = document.querySelector('video');
                        if (v) { v.muted = true; v.play(); }
                    """)
                except:
                    pass

            start_time = time.time()
            while not m3u8_urls and time.time() - start_time < max_wait:
                time.sleep(0.5)
                if int((time.time() - start_time) * 2) % 5 == 0:
                    try:
                        page.evaluate("window.scrollBy(0, 100)")
                    except:
                        pass

            browser.close()

    except Exception as e:
        return name, display_name, [], str(e)

    results = []
    seen = set()
    for m3u8 in m3u8_urls:
        cleaned = clean_m3u8_url(m3u8)
        if cleaned not in seen:
            seen.add(cleaned)
            results.append(cleaned)

    return name, display_name, results, None


def generate_m3u(results, filename="cctv_live.m3u"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write("#EXTM3U\n")
        f.write("# Generated by CCTV Live Scraper (Stable Edition)\n\n")

        success_count = 0
        for name, display_name, urls, error in results:
            if urls:
                success_count += 1
                for idx, url in enumerate(urls):
                    # tvg-id 和 tvg-name 保持一致，都用 display_name
                    f.write(f'#EXTINF:-1 tvg-id="{display_name}" tvg-name="{display_name}" group-title="CCTV",{display_name}\n')
                    f.write(f"{url}\n\n")

    print(f"\nM3U file generated! {success_count} channels")
    print(f"Saved as: {filename}")


def run_all_channels(max_workers=4, max_wait=30):
    total = len(CHANNELS)
    print(f"\nStarting scrape, {total} channels, max {max_workers} processes...\n")

    args_list = [(name, disp_name, url, max_wait) for name, disp_name, url in CHANNELS]

    all_results = []
    with Pool(processes=max_workers) as pool:
        for result in pool.imap_unordered(extract_channel_worker, args_list):
            name, display_name, urls, error = result
            if error:
                print(f"[ERR] [{name}] {error}")
            else:
                status = "OK" if urls else "WARN"
                print(f"[{status}] [{name}] {len(urls)} sources")
            all_results.append(result)

    order_map = {name: idx for idx, (name, _, _) in enumerate(CHANNELS)}
    all_results.sort(key=lambda x: order_map[x[0]])

    generate_m3u(all_results)

    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)
    for name, display_name, urls, error in all_results:
        if error:
            print(f"[ERR] {display_name:12} -> {error[:50]}")
        elif urls:
            print(f"[OK]  {display_name:12} -> {len(urls)} sources")
            for u in urls:
                print(f"      {u[:80]}...")
        else:
            print(f"[WARN] {display_name:12} -> no sources found")

    json_data = {}
    for name, display_name, urls, _ in all_results:
        if urls:
            json_data[display_name] = urls
    
    with open("cctv_live.json", "w", encoding="utf-8") as f:
        json.dump(json_data, f, ensure_ascii=False, indent=2)
    print(f"\nJSON backup: cctv_live.json")

    return all_results


if __name__ == "__main__":
    MAX_WORKERS = 4
    MAX_WAIT = 35
    results = run_all_channels(max_workers=MAX_WORKERS, max_wait=MAX_WAIT)
